name       : qt5-webchannel
version    : 5.14.2
release    : 19
source     :
    - https://download.qt.io/official_releases/qt/5.14/5.14.2/submodules/qtwebchannel-everywhere-src-5.14.2.tar.xz : 7d1dc8441523638c3d455c7d408ec65aebc073acab80e24063865f929231f874
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-or-later
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt5 Webchannel Module
description: |
    The Qt WebChannel module offers Qt applications a seamless way to publish `QObjects` for interaction
    with HTML/JavaScript clients. These clients can either be inside local Qt `WebView`s or any other,
    potentially remote, client which supports JavaScript, as long as a communication channel such
    as WebSocket is available.
    Qt WebChannel uses introspection on the `QObject`s and sends this serialized data to the clients.
    There, with the help of a small JavaScript library, an object is created which simulates the API of
    the `QObject`. Any invokable methods, including slots, can be called as well as properties read and
    written. Additionally you can connect to signals and register JavaScript callbacks as handlers.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5WebSockets)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtwebchannel.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
