name       : qt5-webchannel
version    : 5.10.0
release    : 8
source     :
    - https://download.qt.io/official_releases/qt/5.10/5.10.0/submodules/qtwebchannel-everywhere-src-5.10.0.tar.xz : f22424dc6235110bb7f587b01ce692738af1497fba2a9739fa90a5e57ba135a3
license    :
    - GFDL-1.3
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Webchannel Module
description: |
    The Qt WebChannel module offers Qt applications a seamless way to publish `QObjects` for interaction
    with HTML/JavaScript clients. These clients can either be inside local Qt `WebView`s or any other,
    potentially remote, client which supports JavaScript, as long as a communication channel such
    as WebSocket is available.
    Qt WebChannel uses introspection on the `QObject`s and sends this serialized data to the clients.
    There, with the help of a small JavaScript library, an object is created which simulates the API of
    the `QObject`. Any invokable methods, including slots, can be called as well as properties read and
    written. Additionally you can connect to signals and register JavaScript callbacks as handlers.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5WebSockets)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtwebchannel.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
